# Generated by Django 4.1.1 on 2022-09-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_alter_hotelproperty_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='facility_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
