# Generated by Django 4.1.1 on 2022-09-26 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_alter_image_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='room',
        ),
        migrations.AddField(
            model_name='image',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.hotelproperty'),
        ),
        migrations.AlterField(
            model_name='image',
            name='upload',
            field=models.ImageField(upload_to='hotel_<django.db.models.fields.related.ForeignKey>/'),
        ),
    ]
