# Generated by Django 4.1.1 on 2022-09-26 10:40

from django.db import migrations, models
import hotels.models.hotel_models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0010_alter_image_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='upload',
            field=models.ImageField(upload_to=hotels.models.hotel_models.user_directory_path),
        ),
    ]
