# Generated by Django 4.1.1 on 2022-09-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0014_alter_address_city_alter_address_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelproperty',
            name='facility',
            field=models.ManyToManyField(null=True, related_name='hotel_facility', to='hotels.facility'),
        ),
    ]
