# Generated by Django 4.1.1 on 2022-09-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='description',
        ),
        migrations.AddField(
            model_name='hotelproperty',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hotelproperty',
            name='facility',
            field=models.ManyToManyField(null=True, to='hotels.facility'),
        ),
    ]
