# Generated by Django 4.1.1 on 2022-09-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_remove_room_description_hotelproperty_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelproperty',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
