# Generated by Django 4.1.1 on 2022-09-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0009_alter_image_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='upload',
            field=models.ImageField(upload_to='hotels/static/images/hotel_<django.db.models.fields.related.ForeignKey>/'),
        ),
    ]
