# Generated by Django 4.1.1 on 2022-09-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0011_alter_image_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelproperty',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='upload',
            field=models.ImageField(upload_to='hotels/static/images/hotel/'),
        ),
    ]
