# Generated by Django 4.1.1 on 2022-09-26 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0012_alter_hotelproperty_description_alter_image_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelproperty',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='hotels.address'),
        ),
        migrations.AlterField(
            model_name='image',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_img', to='hotels.hotelproperty'),
        ),
        migrations.AlterField(
            model_name='room',
            name='facility',
            field=models.ManyToManyField(blank=True, null=True, related_name='facility', to='hotels.facility'),
        ),
        migrations.AlterField(
            model_name='room',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel', to='hotels.hotelproperty'),
        ),
    ]
